sudo: required
dist: trusty
before_install:
- "sudo apt-get update -q && sudo apt-get install -yq --no-install-recommends texlive-full python-pygments gnuplot"
script:
- mkdir _build
#http://unix.stackexchange.com/questions/118217/chmod-silent-mode-how-force-exit-code-0-in-spite-of-error
- pdflatex -interaction=nonstopmode -output-directory _build inaki_anduaga_cv.tex || true
deploy:
  provider: releases
  api_key:
    secure: OOf0Rcct6ONSTZ7Saps0QuaffV0bPYrbvuAg1pJdlRD3lG3WjzIfbGKlorTpDmC8yrjw9Vx5Ci3cv5EyfiHcKlAmWu+vfxjxJKFZoufPFyY9A9xVKOfMfJeMrR2etJgVcixaN1I5x8FXMJgJFhGg5aJoP7qg35gfyv+U57lT3aa058ufSicL3eXejSyv6P1Jlcmf+9Sr6ks2DQzBTKI9lEDH6oUld6tzkTgnFSLg9pB2bwtQgl6gtg5RceDcTUknZ15cZCLjyigLdJUkmP1+6MH5D97oiMaB3ijh2tEQJfE05fKGZMFGSsVbjOJPGExi6DV9LGZkYn6l61A+sYWYcEPce5dSCmkjeP5TpzCqY7o3EAuxIs597MwQBQMi539raQkISrpZ41t0rdGnb/zeUyBLdbNvZjAxn5UAt0KUHvf2EWoes3Dz7qc2QVfE/JGmwCmAXEF6iuO2Em/O6r3OKi7uuzwdqSFHZdq8a0NpdkOrF6wn0lfXHWO0s64S40sMriVqGrnrhVUGbmy9GfZV5mGCgxnViORs+Yxoxb8pRL8cw7dp/319yj/W6HFO1XI1bZfRC255lOMQeHpqp+A1RjvVvZ5bJG4duztJw4AvjhtW8+i36+M1UFtTMl+wzDjH1YBkgBYxHxgw0eh95akXlsDklREhhIZONpdiD6V9ctA=
  file:
  - _build/inaki_anduaga_cv.pdf
  skip_cleanup: true
  on:
    repo: inakianduaga/cv
    branch: master
    tags: true
