sudo: required
dist: trusty
# services:
#   - docker
before_install:
  - docker pull blang/latex
script:
  - mkdir _build
  #http://unix.stackexchange.com/questions/118217/chmod-silent-mode-how-force-exit-code-0-in-spite-of-error
  - docker run --rm -i --net=none -v $PWD:/data blang/latex pdflatex -interaction=nonstopmode --output-directory=./_build inaki_anduaga_cv.tex || true
  # Give back ownership of file to current user
  - sudo chown -R $USER:$USER ./_build
  # Remove non-pdf files from build folder
  - find ./_build -type f ! -name '*.pdf' -delete
deploy:
  # Github Release
  - provider: releases
    api_key:
      secure: B2vDLHBWS25hV3Q6CQHnz5rTdrL8RUdSj54XCL4vobuhwW+UxQX1FIbCD/SHf7nEmOIeH+Elwkp2D7MHJxTyNgiOIlZ945zDDo3qLvx9eJFi2zXX+LO/+YkjJIhUnwcGrC3TC2eT4pG9pheYpk8eyt6oR0YBIlTEPa4JDl2h+yWJSPfmwFMeB8sEc/BWT9ewXyqrDeRhfedjVtZnnI4CCBwJid4D0c5YRRyQU1qjnNfxjkZc+DnJ8037hrls+ShLj/LlX1E2PsXQ12W6sgKsjXYAkpiwdOWCiv2UslLgKj2IKse60MXCQq37jTzRxjJc7C6xVR/ru3UsduSpHS0vvH+GZQfmd8vS2oQ3d5i2o9qgh7GuxbjbSHf4jgM3Go50yAuV3KpnONwPGxuydAe90e5m6aCNvRTkrSBa5YCr2Wjqy/JtZ/dCDdt8Cd9KRCCpA0dhFFwpe0eYxyPs0vJr8ERakssep+MKEMymMBPak/u9YE8Z+/LbXiuKNePnbPg5KhS9uWKplD1pZdzOErU8y4yjx8MOCJynLW3WlByArpT97P7OllWJWKZ2A8QblndZYDw4VVsgdEsRNgUiNJM/p2P3Tl7spPHZaPn+Fb3EJ6EuxDDFNIbwzQy5g83wLI6LIMz9fMb0QnSDc8LFfcwm/OfQ5z2nh9dNiqxmmOrYkKw=
    file:
      - _build/inaki_anduaga_cv.pdf
    skip_cleanup: true
    on:
      repo: inakianduaga/cv
      tags: true
  # AWS S3 deployment
  - provider: s3
    access_key_id: AKIAIHZWB2UXGOWZV7MA
    secret_access_key:
      secure: e7YgoOhC52ARTrZFTr6tGA5UpAr/eGe95k353suDlV9AztMh2a6DAcJ0NWslEBNNa/p9fXTPC6cWP9oqaKxU3qGJ/B1jYotXgGPYOykq9aTGdG9Jcofn2ash8VmQsj3juAs3/GUTEI0Zpgz+kWUi9dxJeX6UuTW8mpJO21IRLUqFSH06UAoN7/IRHfdRR8tEr28f7MrcLMA/4vh00clqOKCDIhw746zDCiiE+CHgpTbHT3WvtGZYCNEfA+oWP91kCWWE/lwiBoOj/byQX4v81XZQGfgmmxYspMTWJCBgEG7kTfaTlPk3nCeiATsR+AFQsoO5iWX2iQ66BLe6NoYPIHnG9LOUgGGUX/ieeAb+YUZlu/jySMySNjdkZ1MCIcmmtm9u990TXwA/R5NKh7XGkAuXDgWWweF3lIyPCqpK6Vho0x3dt+siH2dcYXBYalTZRpxm8HXb/9qaKiH17QmBvlezhjaEDN9sKnIqAI0hNrlpOJ8AjgK4KVNyI5FFXPAKGtk1KZ6cKPxGAiCEbzuFSHnkCRpiETjb0svM7I8yLDl5D55Oqur2h/Jvf72xFIbi3++S3UcEFqdoKefjuhR/J89Ph5CMrjjdYKYTZtRTpcyh/hqKdPslce1OYachShbZSkuwI1a5oKStc5H4AYA5+aJ61AEqOPx2DJqe14825Zw=
    bucket: curriculum-vitae-automated-build
    local-dir: _build
    acl: public_read
    skip_cleanup: true
    on:
      repo: inakianduaga/cv
      tags: true
