sudo: required
services:
  - docker
before_install:
- docker pull blang/latex
#- "sudo apt-get update -q && sudo apt-get install -yq --no-install-recommends texlive-full python-pygments gnuplot"
script:
- mkdir _build
# - pdflatex -interaction=nonstopmode -output-directory _build inaki_anduaga_cv.tex || true
#http://unix.stackexchange.com/questions/118217/chmod-silent-mode-how-force-exit-code-0-in-spite-of-error
- docker run --rm -i --net=none -v $PWD:/data blang/latex pdflatex -interaction=nonstopmode --output-directory=./_build inaki_anduaga_cv.tex || true
deploy:
  # AWS S3 deployment
  - provider: s3
    access_key_id: AKIAIHZWB2UXGOWZV7MA
    secret_access_key:
    secure: e7YgoOhC52ARTrZFTr6tGA5UpAr/eGe95k353suDlV9AztMh2a6DAcJ0NWslEBNNa/p9fXTPC6cWP9oqaKxU3qGJ/B1jYotXgGPYOykq9aTGdG9Jcofn2ash8VmQsj3juAs3/GUTEI0Zpgz+kWUi9dxJeX6UuTW8mpJO21IRLUqFSH06UAoN7/IRHfdRR8tEr28f7MrcLMA/4vh00clqOKCDIhw746zDCiiE+CHgpTbHT3WvtGZYCNEfA+oWP91kCWWE/lwiBoOj/byQX4v81XZQGfgmmxYspMTWJCBgEG7kTfaTlPk3nCeiATsR+AFQsoO5iWX2iQ66BLe6NoYPIHnG9LOUgGGUX/ieeAb+YUZlu/jySMySNjdkZ1MCIcmmtm9u990TXwA/R5NKh7XGkAuXDgWWweF3lIyPCqpK6Vho0x3dt+siH2dcYXBYalTZRpxm8HXb/9qaKiH17QmBvlezhjaEDN9sKnIqAI0hNrlpOJ8AjgK4KVNyI5FFXPAKGtk1KZ6cKPxGAiCEbzuFSHnkCRpiETjb0svM7I8yLDl5D55Oqur2h/Jvf72xFIbi3++S3UcEFqdoKefjuhR/J89Ph5CMrjjdYKYTZtRTpcyh/hqKdPslce1OYachShbZSkuwI1a5oKStc5H4AYA5+aJ61AEqOPx2DJqe14825Zw=
    bucket: curriculum-vitae-automated-build
    local-dir: _build
    acl: public_read
    skip_cleanup: true
    on:
      repo: inakianduaga/cv
      tags: true
  # Github Release
  - provider: releases
    api_key:
      secure: OOf0Rcct6ONSTZ7Saps0QuaffV0bPYrbvuAg1pJdlRD3lG3WjzIfbGKlorTpDmC8yrjw9Vx5Ci3cv5EyfiHcKlAmWu+vfxjxJKFZoufPFyY9A9xVKOfMfJeMrR2etJgVcixaN1I5x8FXMJgJFhGg5aJoP7qg35gfyv+U57lT3aa058ufSicL3eXejSyv6P1Jlcmf+9Sr6ks2DQzBTKI9lEDH6oUld6tzkTgnFSLg9pB2bwtQgl6gtg5RceDcTUknZ15cZCLjyigLdJUkmP1+6MH5D97oiMaB3ijh2tEQJfE05fKGZMFGSsVbjOJPGExi6DV9LGZkYn6l61A+sYWYcEPce5dSCmkjeP5TpzCqY7o3EAuxIs597MwQBQMi539raQkISrpZ41t0rdGnb/zeUyBLdbNvZjAxn5UAt0KUHvf2EWoes3Dz7qc2QVfE/JGmwCmAXEF6iuO2Em/O6r3OKi7uuzwdqSFHZdq8a0NpdkOrF6wn0lfXHWO0s64S40sMriVqGrnrhVUGbmy9GfZV5mGCgxnViORs+Yxoxb8pRL8cw7dp/319yj/W6HFO1XI1bZfRC255lOMQeHpqp+A1RjvVvZ5bJG4duztJw4AvjhtW8+i36+M1UFtTMl+wzDjH1YBkgBYxHxgw0eh95akXlsDklREhhIZONpdiD6V9ctA=
    file: _build/inaki_anduaga_cv.pdf
    skip_cleanup: true
    on:
      repo: inakianduaga/cv
      tags: true
