sudo: required
dist: trusty
# services:
#   - docker
before_install:
  - docker pull blang/latex
script:
  - mkdir _build
  #http://unix.stackexchange.com/questions/118217/chmod-silent-mode-how-force-exit-code-0-in-spite-of-error
  - docker run --rm -i --net=none -v $PWD:/data blang/latex pdflatex -interaction=nonstopmode --output-directory=./_build inaki_anduaga_cv.tex || true
  # Give back ownership of file to current user
  - sudo chown -R $USER:$USER ./_build
  # Remove non-pdf files from build folder
  - find ./_build -type f ! -name '*.pdf' -delete
deploy:
  # Github Release
  - provider: releases
    api_key:
      secure: hE1yJ5YZByEmRzopTsna+mY1mRGk1usibo9slzkq+aj4dQhV1n/ZKIGCp1sYeTf0Z34Vsujtz8xOSMagMZZel7vITG0jqgGtgPpeshxnwW4K2X7TtAhK69CSZ92gwZa8GCgU/Y2jWlRv4sJVcPecARnCtPwSmzZMHiGYxucaX2k/L68GVXW+E01EVfM5NGb6edVlk3am1pctmwzIS4Bft6SaX5O3oEl6WeHK5cW1LcZ0YsBCocbyUBL0ETvYfVjlXOkJ6oMAJyyPYGIetucyyG5alWWRk6Mxn5r4rHw2Df2tV4poEV24Ck/2gQSfESzf298SCcTJ5pzUIkwE/cjU4PTkDu2letb34J6cPC559LgmDjor8c3p9FZo1igAYDsgv4zpuLdECa7RM76FRNXbBCQcwDm0NzC075t4djFQ5+l0Ot84wmxcQtmDwWJjPGtDnVXgMueaC7g7Ops9DTyfYU0xsB7Ep/AXxWVM7aM/1T5Da9fZbI2zjqq0UlYEOyyZH/YYCn090w53nSJWq74J0fUbi4QdgCiiHx/YErCSLYj16gAtEKge1bSDfF9h3kXxStQDtwHrdWk31rdy+PUTEN2tWv9hrML/IULygCQFem3p/tx9vcvG/+OnoZnyHQTBKJmn3SMjU1M3d+jjQItS9OJnvctlSDX5QtiSpZjmWZY=
    file:
      - _build/inaki_anduaga_cv.pdf
    skip_cleanup: true
    on:
      repo: inakianduaga/cv
      tags: true
  # AWS S3 deployment
  - provider: s3
    access_key_id: AKIAIHZWB2UXGOWZV7MA
    secret_access_key:
      secure: e7YgoOhC52ARTrZFTr6tGA5UpAr/eGe95k353suDlV9AztMh2a6DAcJ0NWslEBNNa/p9fXTPC6cWP9oqaKxU3qGJ/B1jYotXgGPYOykq9aTGdG9Jcofn2ash8VmQsj3juAs3/GUTEI0Zpgz+kWUi9dxJeX6UuTW8mpJO21IRLUqFSH06UAoN7/IRHfdRR8tEr28f7MrcLMA/4vh00clqOKCDIhw746zDCiiE+CHgpTbHT3WvtGZYCNEfA+oWP91kCWWE/lwiBoOj/byQX4v81XZQGfgmmxYspMTWJCBgEG7kTfaTlPk3nCeiATsR+AFQsoO5iWX2iQ66BLe6NoYPIHnG9LOUgGGUX/ieeAb+YUZlu/jySMySNjdkZ1MCIcmmtm9u990TXwA/R5NKh7XGkAuXDgWWweF3lIyPCqpK6Vho0x3dt+siH2dcYXBYalTZRpxm8HXb/9qaKiH17QmBvlezhjaEDN9sKnIqAI0hNrlpOJ8AjgK4KVNyI5FFXPAKGtk1KZ6cKPxGAiCEbzuFSHnkCRpiETjb0svM7I8yLDl5D55Oqur2h/Jvf72xFIbi3++S3UcEFqdoKefjuhR/J89Ph5CMrjjdYKYTZtRTpcyh/hqKdPslce1OYachShbZSkuwI1a5oKStc5H4AYA5+aJ61AEqOPx2DJqe14825Zw=
    bucket: curriculum-vitae-automated-build
    local-dir: _build
    acl: public_read
    skip_cleanup: true
    on:
      repo: inakianduaga/cv
      tags: true
